@host=http://localhost:8080

##################################################
# Variables
##################################################

@accessToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ1c2VyIiwidXNlcklkIjozLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzg1OTEwMDQyLCJleHAiOjE3ODU5MTM2NDJ9.hfYwJKj7Lx7Tu-V4ji-1W6WkPOFxxKqvThvEXZ1yDbQ_3MBuAS0VtDajkvyZrujI
@refreshToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ1c2VyIiwidXNlcklkIjozLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzg1OTEwMDQyLCJleHAiOjE3ODcxMTk2NDJ9.P81A5WMt6oM2PU5EEVlI-fkC4Rth4ivI1uhbTHMvME1Gu8ryU7DLuHISTRKYKMCq

##################################################
# Public API
##################################################

###
GET {{host}}/api/test/public

##################################################
# Login - ADMIN
##################################################

###
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

##################################################
# Login - PM
##################################################

###
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "pm",
  "password": "pm1234"
}

##################################################
# Login - USER
##################################################

###
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "user1234"
}

##################################################
# Refresh Token
##################################################

###
POST {{host}}/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

##################################################
# JWT Authentication Test
##################################################

###
GET {{host}}/api/test/private
Authorization: Bearer {{accessToken}}

##################################################
# Role Test
##################################################

### Authenticated
GET {{host}}/api/role/authenticated
Authorization: Bearer {{accessToken}}

###

### USER
GET {{host}}/api/role/user
Authorization: Bearer {{accessToken}}

###

### PM
GET {{host}}/api/role/pm
Authorization: Bearer {{accessToken}}

###

### ADMIN
GET {{host}}/api/role/admin
Authorization: Bearer {{accessToken}}

##################################################
# Temporary Token API
# feature/auth-refresh 완료 후 삭제 예정
##################################################

###
GET {{host}}/api/test/token